### PR TITLE
New kwarg for SlashClient

### PR DESCRIPTION
**Pull request by m1raynee**
modify_send: If `False`, `.send` and `.edit` methods will not modified. This means that you will not be able to use the message components.

### CODE REVIEW

**Comment by m1raynee** [comment]
I think this is not finished yet because my code is still getting errors when I use the experimental version of dpy. I want this argument to stop all work with message components. In the current case I want to use dislash for slash commands only.

**Comment by EQUENOS** [comment]
We already figured out what caused the error, it'll be fixed in the next patch.
Speaking of the new kwarg, I think there's indeed a point in having it, thanks for the PR!

**Comment by m1raynee** [comment]
I have new idea for that problem! Let's imagine a perfect world where everything is perfect. As I imagine it: new `IncludeType` class and new `include` kwarg  to replace the old one. 
```py
class IncludeType:
    ALL = 0
    SLASH_COMMANDS = 1
    MESSAGE_COMPONENTS = 2


class SlashClient:
    def __init__(self, client, *, show_warnings: bool=False, include: Union[IncludeType, int] = 0): ...
        # do something to activate only what is said in include
    

# in bot's main file:
slash = SlashClient(bot, include=IncludeType.SLASH_COMMANDS)
```
~~Hope I didn't overdo~~

**Comment by m1raynee** [comment]
I asked myself this question. after a long review of the source code, I still don't fully understand if it is possible to separate slash commands from message components. Therefore, I want to know if this is possible in theory. Of course, I can rollback several updates back on it, but I don't think this is the best solution.

**Comment by EQUENOS** [comment]
Well, there's a method in `SlashClient` called `_process_interaction`. It looks at the interaction type and wraps it up using the relevant class. It's absolutely possible to disable the track of a specific interaction type, however, you also want to completely turn off all functions corresponding to it, so I don't know if this is easy to implement.
Anyways, we have a ton of other work to do, which may be more important at the current stage of development, but thanks for the PR!

**Comment by m1raynee** [comment]
Okay, okay, got it. And here you are.

**Pull request merged**
